In [3]:
import numpy as np

In [7]:
A = np.array([[56.0, 0.0, 4.4, 68.0],
              [1.2, 104.0, 56.0, 8.0],
              [1.8, 135.0, 99.0, 0.0]])

In [18]:
A

array([[ 56. ,   0. ,   4.4,  68. ],
       [  1.2, 104. ,  56. ,   8. ],
       [  1.8, 135. ,  99. ,   0. ]])

In [31]:
cal = A.sum(axis=0)

In [32]:
cal

array([ 59. , 239. , 159.4,  76. ])

In [25]:
rs = cal.reshape(1,4)

In [26]:
rs

array([[ 59. , 239. , 159.4,  76. ]])

In [27]:
per = 100* A/rs

In [28]:
per

array([[94.91525424,  0.        ,  2.76035132, 89.47368421],
       [ 2.03389831, 43.51464435, 35.13174404, 10.52631579],
       [ 3.05084746, 56.48535565, 62.10790464,  0.        ]])

In [37]:
x = np.array([[1,2,3,4]])
y = np.array([[100]])

z=x+y

In [38]:
z

array([[101, 102, 103, 104]])

In [44]:
x1 = np.array([[1,2,3],
              [4,5,6]])
y1 = np.array([[100,200,300]])

z1 = x1+y1

In [45]:
z1

array([[101, 202, 303],
       [104, 205, 306]])

In [64]:
y2 = np.array([[100],
              [200]])

z2 = x1/y2

In [65]:
z2

array([[0.01 , 0.02 , 0.03 ],
       [0.02 , 0.025, 0.03 ]])