In [1]:
import numpy as np

In [20]:
a = np.random.rand(5)

In [21]:
a

array([0.88095997, 0.30964343, 0.22332337, 0.1379267 , 0.61070478])

In [22]:
print(a.shape)

(5,)


In [23]:
a.T

array([0.88095997, 0.30964343, 0.22332337, 0.1379267 , 0.61070478])

In [24]:
print(np.dot(a,a.T))

1.3138269621119825


In [34]:
x = np.random.rand(4,4)

In [35]:
x

array([[0.86854655, 0.13312936, 0.20006479, 0.67833184],
       [0.50424691, 0.94942074, 0.82040028, 0.60191606],
       [0.48372353, 0.9921369 , 0.37251621, 0.66915171],
       [0.5965522 , 0.60773053, 0.65930236, 0.59411448]])

In [36]:
x.T

array([[0.86854655, 0.50424691, 0.48372353, 0.5965522 ],
       [0.13312936, 0.94942074, 0.9921369 , 0.60773053],
       [0.20006479, 0.82040028, 0.37251621, 0.65930236],
       [0.67833184, 0.60191606, 0.66915171, 0.59411448]])

In [26]:
b = np.random.rand(5,1)

In [28]:
b

array([[0.19337147],
       [0.42192005],
       [0.89318978],
       [0.63183192],
       [0.83983722]])

In [37]:
print(b.T)

[[0.19337147 0.42192005 0.89318978 0.63183192 0.83983722]]


In [39]:
print(np.dot(b,b.T)) #Dot Product

[[0.03739253 0.0815873  0.17271742 0.12217827 0.16240056]
 [0.0815873  0.17801653 0.37685468 0.26658256 0.35434416]
 [0.17271742 0.37685468 0.79778799 0.56434582 0.75013402]
 [0.12217827 0.26658256 0.56434582 0.39921158 0.53063596]
 [0.16240056 0.35434416 0.75013402 0.53063596 0.70532655]]


In [42]:
a = np.random.randn(2, 3) # a.shape = (2, 3)
b = np.random.randn(2, 1) # b.shape = (2, 1)
c = a + b
np.shape(c)

(2, 3)

In [43]:
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)
np.shape(c)

(12288, 45)

In [44]:
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(3, 2) # b.shape = (3, 2)
c = a*b

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [46]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
np.shape(c)

(3, 3)